### ISSUE TITLE
大佬什么时候更新支持最新retrofit2啊？

### ISSUE THREAD

**Issue by General110** [yale8848/RetrofitCache#35]
大佬什么时候更新支持最新retrofit2啊？

**Comment by yale8848** [comment]
本身就支持啊

**Comment by General110** [comment]
retrofit2 2.5.0 


java.lang.NoSuchFieldException: No field serviceMethod in class Lretrofit2/OkHttpCall; (declaration of 'retrofit2.OkHttpCall' appears in /data/app/com.meiju592.app-jZ2dntm5XqmsAln3ap5tng==/base.apk!classes34.dex)
2019-04-20 15:04:08.195 8380-8380/com.meiju592.app W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
2019-04-20 15:04:08.195 8380-8380/com.meiju592.app W/System.err:     at ren.yale.android.retrofitcachelibrx2.transformer.CacheTransformer.observable(CacheTransformer.java:64)
2019-04-20 15:04:08.195 8380-8380/com.meiju592.app W/System.err:     at ren.yale.android.retrofitcachelibrx2.transformer.CacheTransformer.access$000(CacheTransformer.java:14)
2019-04-20 15:04:08.195 8380-8380/com.meiju592.app W/System.err:     at ren.yale.android.retrofitcachelibrx2.transformer.CacheTransformer$1.apply(CacheTransformer.java:29)
2019-04-20 15:04:08.195 8380-8380/com.meiju592.app W/System.err:     at io.reactivex.Observable.compose(Observable.java:6283)

**Comment by General110** [comment]
retrofit2 2.5.0

java.lang.NoSuchFieldException: No field serviceMethod in class Lretrofit2/OkHttpCall; (declaration of 'retrofit2.OkHttpCall' appears in /data/app/com.app.app-jZ2dntm5XqmsAln3ap5tng==/base.apk!classes34.dex)
2019-04-20 15:04:08.195 8380-8380/com.app.app W/System.err: at java.lang.Class.getDeclaredField(Native Method)
2019-04-20 15:04:08.195 8380-8380/com.app.app W/System.err: at ren.yale.android.retrofitcachelibrx2.transformer.CacheTransformer.observable(CacheTransformer.java:64)
2019-04-20 15:04:08.195 8380-8380/com.app.app W/System.err: at ren.yale.android.retrofitcachelibrx2.transformer.CacheTransformer.access$000(CacheTransformer.java:14)
2019-04-20 15:04:08.195 8380-8380/com.app.app W/System.err: at ren.yale.android.retrofitcachelibrx2.transformer.CacheTransformer$1.apply(CacheTransformer.java:29)
2019-04-20 15:04:08.195 8380-8380/com.app.app W/System.err: at io.reactivex.Observable.compose(Observable.java:6283)

retrofit2 2.2.0 没有问题

**Comment by yale8848** [comment]
好的，2.5.0下版本支持

**Comment by yale8848** [comment]
1.1.0 release
